version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    environment:
      BUNDLE_PATH: /bundle/vendor
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_path:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_path:
  db_data: